name: Publish Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.AUTH_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Set package repo auth to .npmrc file
        run: |
          echo -e "\n//npm.pkg.github.com/:_authToken=${{ env.NODE_AUTH_TOKEN }}" >> .npmrc

      - uses: pnpm/action-setup@v4.1.0

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint
      
      - name: Publish
        run: pnpm publish --no-git-checks